from enum import Enum

class ErrorResponseStatus(Enum):
    INVALID_FIELD = 'INVALID_FIELD'
    USER_NOT_FOUND = 'USER_NOT_FOUND'
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS'
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'